Autocomplete Update
ppauel/typescript-discord-bot pull request #9
Opened 2023-03-19 02:42 UTC by bowenjw

### Changes
- Added support for autocomplete
- Added example for autocomplete
- Added example for models
- Updated all modules to latest version

**_Note: Documentation needs to be updated for changes_**

## Autocomplete
Autocomplete is now an optional function include in the `ChatInputCommand` interface
```ts
export interface ChatInputCommand extends Command {
    options: SlashCommandBuilder | SlashCommandSubcommandsOnlyBuilder | Omit<SlashCommandBuilder, 'addSubcommand' | 'addSubcommandGroup'>
    execute(client: ExtendedClient, interaction: ChatInputCommandInteraction): Promise<void>,
    autocomplete?(interaction: AutocompleteInteraction): Promise<void>
}
```
When an autocomplete interaction is received, the `ChatInputCommand` object is validated that it has the `autocomplete` function
```ts
switch (interaction.type) {
case InteractionType.ApplicationCommandAutocomplete:
    // Check if autocomplete interactions are enabled
    if (!client.config.interactions.receiveAutocomplete) return;
    interactionName = interaction.commandName;
    // eslint-disable-next-line no-case-declarations
    const autocomplete = client.commands.get(interactionName)?.autocomplete;
    if (!autocomplete) { console.warn(`[Warning] Autocomplete for ${interactionName} was not Setup`); }
    else { autocomplete(interaction); }
    break;
}
```

See `src/commands/example/autocomplete.ts` for example of auto complete

## Modal Example
Chat command creates a model window with a `short` and `paragraph` fields
![image](https://user-images.githubusercontent.com/26281339/226150318-6abacd1f-8ae1-4ac2-89dc-b2498504c463.png)
Then replies with an embed containing the text
![image](https://user-images.githubusercontent.com/26281339/226150345-b4bef72a-3776-42a7-b4b1-b36dcf0961dc.png)

## Module Updates
[TypeScript]( https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/) `4.9.4` -> `5.0.2` 
[discord.js](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/CHANGELOG.md) `14.7.1` -> `14.8.0`
[@fluent/bundle](https://github.com/projectfluent/fluent.js/blob/master/fluent-bundle/CHANGELOG.md) `0.17.1` -> `0.18.0`
See `Package.json` for all changes

2023-03-25 20:42 UTC, bowenjw commented
I have overhauled the interfaces and replaced them with classes.

2023-04-10 00:19 UTC, Codeize requested changes

2023-04-10 00:19 UTC, Codeize commented on src/interactions/modals/example/model.ts
Hi, due to the `modal` word being misspelled in the `.setName` method here it causes the modal submit to fail without throwing any error.

It should be:
```diff
- .setName('model')
+ .setName('modal')
```

2023-04-12 23:46 UTC, bowenjw commented on src/interactions/modals/example/model.ts
fixed

2023-04-13 14:26 UTC, Codeize approved these changes

2023-05-14 23:51 UTC, bowenjw commented
Closing pull request as I am because I am working on a different one. Which will will have far exceeded what is in this pull request.

2023-05-14 23:51 UTC, closed without merging